//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUL.Dal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=Elite;User ID=sa;Password=can722count")]
        public string SQLConnectionString {
            get {
                return ((string)(this["SQLConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IT\\SQLEXPRESS;Initial Catalog=Elite;User ID=sa;Password=Elit!23")]
        public string SQLConnectionStringLive {
            get {
                return ((string)(this["SQLConnectionStringLive"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SYSTECH-DEV-PC\\SQLEXPRESS;Initial Catalog=Elite;User ID=sa;Password=s" +
            "a@admin")]
        public string SQLConnectionStringLive2 {
            get {
                return ((string)(this["SQLConnectionStringLive2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SYSTECH-DEV-PC\\SQLEXPRESS;Initial Catalog=EliteLive;User ID=sa;Passwo" +
            "rd=sa@admin")]
        public string SQLConnectionStringLive3 {
            get {
                return ((string)(this["SQLConnectionStringLive3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IT\\SQLEXPRESS;Initial Catalog=EliteTest;User ID=sa;Password=Elit!23")]
        public string SQLConnectionStringTest {
            get {
                return ((string)(this["SQLConnectionStringTest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SYSTECH-DEV-PC\\SQLEXPRESS;Initial Catalog=EliteTest;User ID=sa;Passwo" +
            "rd=sa@admin")]
        public string SQLConnectionStringTest2 {
            get {
                return ((string)(this["SQLConnectionStringTest2"]));
            }
        }
    }
}
